# 错误处理
1. panic: 内部错误
    * 两种原因：检测到某种错误即将发生；调用了宏panic!()
    1. unwinding: 打印错误信息；逐层弹栈释放空间；线程退出。也可以用std::panic::catch_unwind()捕获错误。
    2. aborting: 会终止整个进程。在unwinding的过程中drop某个值时又发生了panic/编译参数 -C panic=abort时发生。
2. Result: 外部错误
    * Result<T, E>: 可以取OK(T)或Err(E)
    * .is_ok()和.is_err()返回bool值，不会消费掉rst
    * .ok()和.err()返回对应的Some(T/E)或非对应的None
    * .unwrap()和.expect(msg)尝试拆出OK(T)里的T，否则失败触发panic，expect还会打印msg
    * .unwrap(fb)和.unwrap_or_else(fb_fn)类似上一行，失败返回fb或fb_fn()的
    * 上述方法会消费掉rst这个值（所有权转移），可以用.as_ref()或.as_mut()